### ISSUE TITLE
put the GUI in bifs_gui

### ISSUE THREAD

**Issue by RossBoylan** [ucsf-deb/bifs#21]
**Low** priority, but ...
`bifs_gui` delivers a lot of its error messages via `print`.  It should instead be popping up graphical widgets with the appropriate message and symbol (error/warning/info...).  `Qt` provides functions to do this, so it shouldn't be too painful.

A quick and dirty solution would be to redefine `print` within `bifs_gui` to invoke one of those functions, but just doing a search and replace is likely safer.

**Comment by kyoung21b** [comment]
Yep, another vestige of the quick dirty development that hasn’t been replaced, though I do recall looking at the QT error widgets and realized that a little care is required re. implementing those; there is some history baked into them, such that there are different mechanisms available and choosing one and staying consistent requires a little work.

— K

**Comment by RossBoylan** [comment]
Basically done by the 0.9.4 release
