### ISSUE TITLE
Error when exiting program, bifs_gui

### ISSUE THREAD

**Issue by dtribose** [ucsf-deb/bifs#24]
There are currently two ways to exit the bifs_gui script:
1.  X - ing out, using the button in the upper right hand corner
2. Using the File menu Exit (or equivalent ctrl-Q)

They should have the same behavior but they do not. 
The first works OK, other than yielding an exit code of -1 (which is usually not a big deal in GUI applications, but indicates an bad/non-normal exit).
 
The second yields the following error:
`NameError: name 'app' is not defined`
This error is not a surprise when looking at the code for the close() method: It is calling a function on the `app` object. That variable is not visible in this function. It is also calling the `exec_()` method on `app`, which I don't think is correct. I believe `exec_` is what is used to start the program.

I did a test, making `app` a global variable, and using `app.quit()`.  That seemed to work OK, but not sure if that is the best way to go.
@kyoung21b, @RossBoylan

**Comment by RossBoylan** [comment]
I pushed 2db1fa467792fb4e8f0790df1eda3fa22e4a7b69 with a note that it fixes this, but no auto-close.
So I'm doing it manually.
