### ISSUE TITLE
'PyQt5.QtCore' has no attribute 'Signal'

### ISSUE THREAD

**Issue by Kornakowski** [ucsf-deb/bifs#30]
Gui not popping up on start up. instead get error

AttributeError: module 'PyQt5.QtCore' has no attribute 'Signal'

Current list of packages in pip environment:

Package         Version
--------------- ---------
bifs            0.9.4
certifi         2021.5.30
cycler          0.10.0
imageio         2.9.0
jsonpickle      2.0.0
kiwisolver      1.3.2
matplotlib      3.4.3
nibabel         3.2.1
numpy           1.21.2
packaging       21.0
Pillow          8.3.2
pip             21.3.1
pyparsing       2.4.7
PyQt5           5.15.6
PyQt5-Qt5       5.15.2
PyQt5-sip       12.9.0
python-dateutil 2.8.2
scipy           1.7.1
setuptools      58.1.0
six             1.16.0
wheel           0.37.0

(bifsenv) (bifsPip) DEB-0FTHX8F-DT:BifsPipTestEnvDir kornak$ bifs_gui
Traceback (most recent call last):
  File "/opt/anaconda3/envs/bifsPip/bin/bifs_gui", line 5, in <module>
    from bifs.bifs_gui import launch
  File "/opt/anaconda3/envs/bifsPip/lib/python3.8/site-packages/bifs/__init__.py", line 8, in <module>
    from bifs.bifscore import BIFS
  File "/opt/anaconda3/envs/bifsPip/lib/python3.8/site-packages/bifs/bifscore.py", line 27, in <module>
    from bifs.bifsexception import *
  File "/opt/anaconda3/envs/bifsPip/lib/python3.8/site-packages/bifs/bifsexception.py", line 187, in <module>
    class UncaughtHook(QtCore.QObject):
  File "/opt/anaconda3/envs/bifsPip/lib/python3.8/site-packages/bifs/bifsexception.py", line 188, in UncaughtHook
    _exception_caught = QtCore.Signal(object)
AttributeError: module 'PyQt5.QtCore' has no attribute 'Signal'

**Comment by RossBoylan** [comment]
The error occurs on a Mac with conda installed, though I think the environment of the error at least attempted to get out of conda.

**Comment by RossBoylan** [comment]
Tagged this as a bug, though it is unclear whether it is a bug in bifs or in the Mac/conda environment and the Qt version there.  On other platforms PyQt5.QtCore  does have the attribute Signal.

Maybe https://groups.google.com/g/pyqtgraph/c/9z-mxO3JyMw?  That problem involved anaconda.
Or use pyqtSignal?
